# Simple configuration for golangci-lint v1.64.6
run:
  timeout: 3m
  tests: true
  go: '1.23.4'

linters:
  disable-all: true
  enable:
    # Core linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Style and formatting
    - gofmt
    - goimports
    - misspell

    # Code quality
    - gosec
    - revive
    - goconst
    - gocyclo

linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'

  goimports:
    local-prefixes: github.com/martiriera/discogs-spotify

  gocyclo:
    min-complexity: 15

  goconst:
    min-occurrences: 3

issues:
  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - gosec
        - gocyclo

  # Maximum count of issues with the same text
  max-same-issues: 5

output:
  formats:
    - format: colored-line-number
      path: stdout

  print-linter-name: true
