steps:
# Build the Go binary
- name: 'golang:1.23'
  entrypoint: 'go'
  args: ['build', '-o', 'server', '.']

# Run tests
- name: 'golang:1.23'
  entrypoint: 'go'
  args: ['test', '-v', './...']

# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/discogs-spotify:$SHORT_SHA', '.']

# Push Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/discogs-spotify:$SHORT_SHA']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'discogs-spotify'
  - '--image'
  - 'gcr.io/$PROJECT_ID/discogs-spotify:$SHORT_SHA'
  - '--set-secrets'
  - 'SPOTIFY_CLIENT_ID=SPOTIFY_CLIENT_ID:latest,SPOTIFY_CLIENT_SECRET=SPOTIFY_CLIENT_SECRET:latest,SESSION_KEY=SESSION_KEY:latest'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--update-env-vars'
  - 'GIN_MODE=release,PORT=8080'

images:
- 'gcr.io/$PROJECT_ID/discogs-spotify:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY