steps:
# Build the Go binary
- name: 'build go binary'
  entrypoint: 'go'
  args: ['build', '-o', 'server', '.']

# Run tests
- name: 'test'
  entrypoint: 'go'
  args: ['test', '-v', './...']

# Build Docker image
- name: 'buid docker image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/discogs-spotify:$SHORT_SHA', '.']

# Push Docker image to Container Registry
- name: 'push docker image'
  args: ['push', 'gcr.io/$PROJECT_ID/discogs-spotify:$SHORT_SHA']

# Deploy to Cloud Run
- name: 'deploy'
  args:
  - 'run'
  - 'deploy'
  - 'discogs-spotify'
  - '--image'
  - 'gcr.io/$PROJECT_ID/discogs-spotify:$SHORT_SHA'
  - '--set-secrets'
  - 'SPOTIFY_CLIENT_ID=SPOTIFY_CLIENT_ID:latest'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--update-env-vars'
  - 'GIN_MODE=release'

images:
- 'gcr.io/$PROJECT_ID/discogs-spotify:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY