services:
  - name: discogs-spotify
    type: web
    runtime: docker
    region: frankfurt
    plan: free
    envVars:
      - key: GIN_MODE
        value: release
      - key: ENV
        value: production
      - key: SPOTIFY_CLIENT_ID
        value: ${SPOTIFY_CLIENT_ID}
      - key: SPOTIFY_CLIENT_SECRET
        value: ${SPOTIFY_CLIENT_SECRET}
      - key: SESSION_KEY
        value: ${SESSION_KEY}
      - key: SPOTIFY_REDIRECT_URI
        value: ${SPOTIFY_REDIRECT_URI}
    dockerContext: .
    dockerfilePath: Dockerfile
